name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --extra dev
        uv pip install build

    - name: Lint with ruff
      id: ruff-check
      run: |
        echo "::group::Ruff Check"
        if ! uv run ruff check .; then
          echo "::error::Ruff check failed. Please run 'ruff check --fix .' locally to fix issues."
          echo "::notice::See contributing guidelines at https://github.com/safevideo/safetext/blob/main/CONTRIBUTING.md"
          exit 1
        fi
        echo "::endgroup::"
        
        echo "::group::Ruff Format"
        if ! uv run ruff format --check .; then
          echo "::error::Ruff format check failed. Please run 'ruff format .' locally to fix formatting."
          echo "::notice::See contributing guidelines at https://github.com/safevideo/safetext/blob/main/CONTRIBUTING.md"
          exit 1
        fi
        echo "::endgroup::"

    - name: Run tests
      run: |
        uv run pytest -v --cov=safetext --cov-report=term-missing -n auto

    - name: Test package installation
      run: |
        uv run python -m build
        uv pip install --no-deps dist/*.whl
        uv run python -c "from safetext import SafeText; st = SafeText('en'); print('Package imported successfully')"