name: Publish Python Package

on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        
    - name: Set up Python
      run: uv python install 3.12
      
    - name: Build package
      run: |
        uv pip install build twine
        uv run python -m build
        
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: uv run twine upload --verbose --skip-existing dist/*